INSERT INTO "Genero" (tipo) VALUES ('Ação');
INSERT INTO "Genero" (tipo) VALUES ('Adulto');
INSERT INTO "Genero" (tipo) VALUES ('Aventura');
INSERT INTO "Genero" (tipo) VALUES ('Animação');
INSERT INTO "Genero" (tipo) VALUES ('Biografia');
INSERT INTO "Genero" (tipo) VALUES ('Comédia');
INSERT INTO "Genero" (tipo) VALUES ('Crime');
INSERT INTO "Genero" (tipo) VALUES ('Documentário');
INSERT INTO "Genero" (tipo) VALUES ('Drama');
INSERT INTO "Genero" (tipo) VALUES ('Família');
INSERT INTO "Genero" (tipo) VALUES ('Fantasia');
INSERT INTO "Genero" (tipo) VALUES ('Film Noir');
INSERT INTO "Genero" (tipo) VALUES ('Game show');
INSERT INTO "Genero" (tipo) VALUES ('História');
INSERT INTO "Genero" (tipo) VALUES ('Horror');
INSERT INTO "Genero" (tipo) VALUES ('Musical');
INSERT INTO "Genero" (tipo) VALUES ('Música');
INSERT INTO "Genero" (tipo) VALUES ('Mistério');
INSERT INTO "Genero" (tipo) VALUES ('Notícia');
INSERT INTO "Genero" (tipo) VALUES ('Reality show');
INSERT INTO "Genero" (tipo) VALUES ('Romance');
INSERT INTO "Genero" (tipo) VALUES ('Ficção científica');
INSERT INTO "Genero" (tipo) VALUES ('Curta-metragem');
INSERT INTO "Genero" (tipo) VALUES ('Esporte');
INSERT INTO "Genero" (tipo) VALUES ('Programa de entrevistas');
INSERT INTO "Genero" (tipo) VALUES ('Suspense');
INSERT INTO "Genero" (tipo) VALUES ('Guerra');
INSERT INTO "Genero" (tipo) VALUES ('Ocidental');